version: "3.9"
services:
  app:
    build: .
    container_name: data-analyst-assistant
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
